---
stages:
  - molecule
  - push

variables:
  GITHUB_USER: lotusnoir
  ANSIBLE_REMOTE_TMP: /tmp
  PY_COLORS: 1

######################################################
# DEFINE CHANGES RULES
######################################################
.molecule_rules:
  rules:
    - changes:
        - "defaults/**"
        - "files/**"
        - "handlers/**"
        - "meta/**"
        - "molecule/**"
        - "tasks/**"
        - "templates/**"
        - "vars/**"
        - "!**/.ansible-lint"
        - "!**/CHANGELOG.md"
        - "!**/CODE_OF_CONDUCT.md"
        - "!**/.gitignore"
        - "!**/.gitlab-ci.yml"
        - "!**/LICENSE"
        - "!**/.pre-commit-config.yaml"
        - "!**/README.md"
        - "!**/.yamllint"
    - when: never

######################################################
# RUN MOLECULE FOR EACH DISTRIB
######################################################
molecule_debian12:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=debian12 molecule test
molecule_debian11:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=debian11 molecule test
molecule_debian10:
  stage: molecule
  image: lotusnoir/molecule_play:v2.0.0
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=debian10 molecule test
molecule_oraclelinux8:
  stage: molecule
  image: lotusnoir/molecule_play:v2.0.0
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=oraclelinux8 molecule test
molecule_oraclelinux9:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=oraclelinux9 molecule test
molecule_redhat8:
  stage: molecule
  image: lotusnoir/molecule_play:v2.0.0
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=redhat8 molecule test
molecule_redhat9:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=redhat9 molecule test
molecule_rocky8:
  stage: molecule
  image: lotusnoir/molecule_play:v2.0.0
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=rocky8 molecule test
molecule_rocky9:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=rocky9 molecule test
molecule_ubuntu20:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  variables:
    MOLECULE_DOCKER_COMMAND: "--cap-add NET_ADMIN"
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=ubuntu20 molecule test
molecule_ubuntu22:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=ubuntu22 molecule test
molecule_ubuntu24:
  stage: molecule
  image: lotusnoir/molecule_play:latest
  extends: .molecule_rules
  script:
    - MOLECULE_DISTRIB=ubuntu24 molecule test


##################################################
# PUSH CODE WHEN ALL TEST OK
##################################################
push_src_on_github:
  stage: push
  image: alpine:latest
  needs:
    - job: molecule_debian12
      optional: true
    - job: molecule_debian11
      optional: true
    - job: molecule_debian10
      optional: true
    - job: molecule_oraclelinux8
      optional: true
    - job: molecule_oraclelinux9
      optional: true
    - job: molecule_redhat8
      optional: true
    - job: molecule_redhat9
      optional: true
    - job: molecule_rocky8
      optional: true
    - job: molecule_rocky9
      optional: true
    - job: molecule_ubuntu20
      optional: true
    - job: molecule_ubuntu22
      optional: true
    - job: molecule_ubuntu24
      optional: true
  before_script:
    - apk add git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GITHUB_USER_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tUser ansible\n\tStrictHostKeyChecking no\n\tForwardAgent yes\n\n" > ~/.ssh/config
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global user.name "${GITHUB_USER}"
    - git config --global init.defaultBranch main
    - COMMENT=$(git log -1 --pretty=%B | head -1)
  script:
    - git clone git@github.com:${GITHUB_USER}/ansible-apps_consul_agent.git /tmp/ansible-apps_consul_agent
    - find /tmp/ansible-apps_consul_agent -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf "{}" +;
    - rm -rf .git
    - cp -r . /tmp/ansible-apps_consul_agent/
    - cd /tmp/ansible-apps_consul_agent
    - git add -A
    - git commit -m "${COMMENT}" || echo "No changes, nothing to commit!"
    - git push --follow-tags
